---
title: "Parametrik olmayan istatistiksel yöntemler ödevi (6)"
author: "Ramazan Erduran"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)  #verilerimizi çekmek için kullandığımız paket
dataset_ex <- read_delim("~/GitHub/Statistical-Analyze/datasets/dataset_ex.csv", 
    delim = "\t", escape_double = FALSE, 
    trim_ws = TRUE)
```

### 300 birimlik örneklem çekme:
  **`readr`** ile çektiğimizi kitlemizden (**dataset_ex**) n=300 birimlik bir örneklem çekiyoruz.  
**`set.seed()`** fonksiyonu ile bu çektiğimiz örneklemi sabitliyoruz ki kodumuz her çalıştığında örneklemmimiz değişmesin.  

```{r data_sample, echo=T}
head(dataset_ex, 3) #kitlemiz
set.seed(300) #kodu her çalıştırdığımızda örneklemimizin değişmemesi için kullandığımız bir fonksiyon
data_sample <- dataset_ex[sample(nrow(dataset_ex),300),replace=F]
head(data_sample, 3)
```

### 9.3 Tabulating Factors and Creating Contingency Tables:
  